/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import java.util.List;
import java.util.Map;

/**
 *
 * @author cody.jones
 */
public class psOrgChartFrame extends javax.swing.JFrame {

    /**
     * Creates new form psOrgChartFrame
     */
    /*We should probably pass the data here for the init*/
    //Map<Integer, List<String>> DataSet
    public psOrgChartFrame() {
        initComponents();
        GenerateOrgChart(/* DataSet */);
    }
    
     public psOrgChartFrame(Map<Integer, List<Integer>> data_sort, Map<Integer, List<String>> data) {
        initComponents();
        GenerateOrgChart(/* DataSet */);
    }
    
    //Position Vars
    private int rowHeight = 75;
    private int rowWidth = 75;
    private int rows = 5;
    private int columns = 5;
    
    public com.psOrgUnitPanel FillerPanel() {
        com.psOrgUnitPanel filler = new com.psOrgUnitPanel("Cody Test", "Test");
        filler.setPreferredSize(new java.awt.Dimension(125,75));
        filler.setBackground(this.getBackground());
        filler.setVisible(false);
        
        return filler;
    }
    
    public void GenerateOrgUnit(String name, String title) {
        this.add(new com.psOrgUnitPanel(name, title));
    }
    
    public void GenerateOrgChart() {
        int width = getContentPane().getWidth();
        
        //com.psOrgUnitPanel OrgUnit = 
        this.setLayout(new java.awt.FlowLayout());
        
        this.add(FillerPanel());
        this.add(FillerPanel());
        this.add(new com.psOrgUnitPanel("Hardeep Gulati", "Chief Executive Officer"));
        this.add(FillerPanel());
        this.add(FillerPanel());
        
        this.add(FillerPanel());
        this.add(FillerPanel());
        this.add(new com.psOrgUnitPanel("Marke Oldemeyer", "Cheif Financial Officer"));
        this.add(FillerPanel());
        this.add(FillerPanel());
        
        this.add(new com.psOrgUnitPanel("Marke Oldemeyer", "Cheif Financial Officer"));
        this.add(new com.psOrgUnitPanel("Marke Oldemeyer", "Cheif Financial Officer"));
        this.add(new com.psOrgUnitPanel("Marke Oldemeyer", "Cheif Financial Officer"));
        this.add(new com.psOrgUnitPanel("Marke Oldemeyer", "Cheif Financial Officer"));
        this.add(new com.psOrgUnitPanel("Marke Oldemeyer", "Cheif Financial Officer"));
        
        this.add(new com.psOrgUnitPanel("Marke Oldemeyer", "Cheif Financial Officer"));
        this.add(new com.psOrgUnitPanel("Marke Oldemeyer", "Cheif Financial Officer"));
        this.add(new com.psOrgUnitPanel("Cody Test", Integer.toString(width)));
        this.add(new com.psOrgUnitPanel("Marke Oldemeyer", "Cheif Financial Officer"));
        this.add(new com.psOrgUnitPanel("Marke Oldemeyer", "Cheif Financial Officer"));
        
        this.add(new com.psOrgUnitPanel("Marke Oldemeyer", "Cheif Financial Officer"));
        this.add(new com.psOrgUnitPanel("Marke Oldemeyer", "Cheif Financial Officer"));
        this.add(new com.psOrgUnitPanel("Cody Test", Integer.toString(width)));
        this.add(new com.psOrgUnitPanel("Marke Oldemeyer", "Cheif Financial Officer"));
        this.add(new com.psOrgUnitPanel("Marke Oldemeyer", "Cheif Financial Officer"));
        
        this.pack();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(psOrgChartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(psOrgChartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(psOrgChartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(psOrgChartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new psOrgChartFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
